### PR TITLE
Get stock and custom icons

### PR DESCRIPTION
**Pull request by frozenice**
I added some things to handle the icons, that includes the standard KeePass icons and custom icons embedded in the database. The standard icons are now bundled in the JAR.

Let me know what you think! I can do `<Binaries>` next. Also write support for both.

### CODE REVIEW

**Comment by ronsmits** [comment]
Personally i wonder if icons belong in openkeepass. I see openkeepass purely as library and i think would leave icon implementation to the consumer of this library.

**Comment by frozenice** [comment]
That crossed my mind, too. I started with returning the data of the custom icons, but then wondered what to do for the stock icons. People might wonder why these behave differently (i.e. they don't get the image data for those). So I made the icon stuff uniform and easy to use.

We certainly could leave the stock icons out, but I prefer libraries that take work off me. (And there isn't any logic forced onto the consumer in that regard.)

**Comment by cternes** [comment]
Thanks David, I will take a closer look at it in the next days.

**Comment by cternes** [comment]
Thank you David for your great work! Don't be disappointed but I refactored a bit to make the API easier to use. However, I really appreciate your work.

**Comment by frozenice** [comment]
No problemo. ;) I don't know your style or the code base very well, so that's expected.
You could add an [.editorconfig file](http://editorconfig.org/), that should with tabs/spaces and some other things.
I'll contribute some more stuff in the future, after I had the chance to play with openkeepass bit.

**Pull request merged**
